export const TYPE_COLORS: Record<string, string> = {
  normal: "from-gray-400 to-gray-500",
  fire: "from-orange-500 to-red-500",
  water: "from-blue-400 to-blue-600",
  electric: "from-yellow-400 to-yellow-500",
  grass: "from-green-400 to-green-600",
  ice: "from-cyan-300 to-cyan-500",
  fighting: "from-red-600 to-red-800",
  poison: "from-purple-500 to-purple-700",
  ground: "from-amber-600 to-amber-800",
  flying: "from-indigo-300 to-indigo-500",
  psychic: "from-pink-500 to-pink-600",
  bug: "from-lime-500 to-lime-600",
  rock: "from-stone-500 to-stone-700",
  ghost: "from-purple-700 to-purple-900",
  dragon: "from-indigo-600 to-purple-600",
  dark: "from-gray-700 to-gray-900",
  steel: "from-slate-400 to-slate-600",
  fairy: "from-pink-300 to-pink-500",
};

export const POKEMON_TYPES = [
  "all",
  "normal",
  "fire",
  "water",
  "electric",
  "grass",
  "ice",
  "fighting",
  "poison",
  "ground",
  "flying",
  "psychic",
  "bug",
  "rock",
  "ghost",
  "dragon",
  "dark",
  "steel",
  "fairy",
] as const;

export type PokemonType = (typeof POKEMON_TYPES)[number];
